### ISSUE TITLE
Discussions没开

### ISSUE THREAD

**Issue by cyb233** [YunYouJun/yun#1]
> 还有什么其他需要补充的，可以去 Discussions 提醒我更新。

Discussions没开

**Comment by YunYouJun** [comment]
🌿 忘了。
![yun-good-with-text](https://user-images.githubusercontent.com/25154432/149853725-07700c00-69b6-4b85-b125-3951a0aef6ee.jpg)

**Comment by YunYouJun** [comment]
开了。
